name: 01-building-block

on:
    push: 

jobs: 
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "Hello World!"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Successfully executed
              run: |
                echo "I will fail"
                exit 0
            - name: Good bye
              run: echo "Good bye!!"
